version: 0.4.0.{build}

environment:
  PYTHONUNBUFFERED: 1
  matrix:
    - PYTHON_VERSION: "35"
    - PYTHON_VERSION: "36"
    - PYTHON_VERSION: "37"
      POST_COMMAND: "coveralls" # Only export coverage in this version

init:
- SET PYTHON=Python%PYTHON_VERSION%
- SET PATH=C:\%PYTHON%;C:\Users\appveyor\AppData\Roaming\Python\%PYTHON%\Scripts;%PATH%
- python -V

build: off

install:
- python -m pip install -U --user pip
- python -m pip install -U --user tox

test_script:
- tox -e py%PYTHON_VERSION%


