environment:
  PYTHONUNBUFFERED: 1
  matrix:
    - PYTHON: "C:\\Python35"
      TOX_ENV: "py35"
    - PYTHON: "C:\\Python36"
      TOX_ENV: "py36"
    - PYTHON: "C:\\Python37"
      TOX_ENV: "py37"

init:
- "%PYTHON%/python -V"

build: off

install:
- "%PYTHON%/Scripts/pip install -U --user pip"
- "%PYTHON%/Scripts/pip install -U --user tox"
- "%PYTHON%/Scripts/pip install -U --user coverage"

test_script:
- "%PYTHON%/python -m tox -e %TOX_ENV%"
- "%PYTHON%/python -m coverage report"



