# pycstruct appveyor configuration for Linux x64

# Common configuration
#image: 
#- Ubuntu

#platform: x64

# Do not build on tags (GitHub and BitBucket)
#skip_tags: true

#version: 0.1.0.{build}

#stack: python 3.5


environment:
  PYTHONUNBUFFERED: 1
  matrix:
    include:
      - PYTHON: "C:\\Python35"
        TOX_ENV: "py35"
      - PYTHON: "C:\\Python36"
        TOX_ENV: "py36"
      - PYTHON: "C:\\Python37"
        TOX_ENV: "py37"

init:
- "%PYTHON%/python -V"


#environment:
#  matrix:
#  - TOXENV: py35
#  - TOXENV: py36
#  - TOXENV: py37

#build: off

install:
- "%PYTHON%/Scripts/pip install -U --user pip"
- "%PYTHON%/Scripts/pip install -U --user tox"

test_script:
- "%PYTHON%/python -m tox -e %TOX_ENV%"



