# pycstruct appveyor configuration for Linux x64

# Common configuration
image: 
- Ubuntu

platform: x64

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

version: 0.1.0.{build}

#stack: python 3.5

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37

#environment:
#  matrix:
#  - TOXENV: py35
#  - TOXENV: py36
#  - TOXENV: py37

#build: off

install:
- pip install tox

test_script:
- tox



