environment:
  PYTHONUNBUFFERED: 1
  matrix:
    - PYTHON: "C:\\Python35"
      TOX_ENV: "py35"
    - PYTHON: "C:\\Python36"
      TOX_ENV: "py36"
    - PYTHON: "C:\\Python37"
      TOX_ENV: "py37"

init:
- "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
- "python -V"

build: off

install:
- "pip install -U --user pip"
- "pip install -U --user tox"
- "pip install -U --user coverage"

test_script:
- "python -m tox -e %TOX_ENV%"
- "python -m coverage report"



