version: 0.1.0.{build}

environment:
  PYTHONUNBUFFERED: 1
  matrix:
    - PYTHON: "Python35"
      TOX_ENV: "py35"
    - PYTHON: "Python36"
      TOX_ENV: "py36"
    - PYTHON: "Python37"
      TOX_ENV: "py37"

init:
- "SET PATH=C:\\%PYTHON%;C:\\Users\\appveyor\\AppData\\Roaming\\Python\\%PYTHON%\\Scripts;%PATH%"
- "python -V"
- "dir C:\\Users\\appveyor\\AppData\\Roaming\\Python\\%PYTHON%\\Scripts"

build: off

install:
- "pip install -U --user pip"
- "pip install -U --user tox"
- "pip install -U --user coverage"

test_script:
- "tox -e %TOX_ENV%"
- "coverage report"



