version: 0.1.0.{build}

environment:
  PYTHONUNBUFFERED: 1
  matrix:
    - PYTHON: "Python35"
      TOX_ENV: "py35"
    - PYTHON: "Python36"
      TOX_ENV: "py36"
    - PYTHON: "Python37"
      TOX_ENV: "py37"

init:
- "SET PATH=C:\\%PYTHON%;C:\\Users\\appveyor\\AppData\\Roaming\\Python\\%PYTHON%\\Scripts;%PATH%"
- "echo %PYTHON%"
- "python -V"

build: off

install:
- "python -m pip install -U --user pip"
- "python -m pip install -U --user tox"
- "python -m pip install -U --user coverage"
- "dir C:\\Users\\appveyor\\AppData\\Roaming\\Python\\%PYTHON%\\Scripts"

test_script:
- "tox -e %TOX_ENV%"
- "coverage run --source=./pycstruct -m unittest discover -s tests/"
- "coverage report"



