version: 0.1.0.{build}

environment:
  PYTHONUNBUFFERED: 1
  matrix:
    - PYTHON: "C:\\Python35"
      TOX_ENV: "py35"
    - PYTHON: "C:\\Python36"
      TOX_ENV: "py36"
    - PYTHON: "C:\\Python37"
      TOX_ENV: "py37"

init:
- "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
- "python -V"
- "dir %PYTHON%\\Scripts"
- "dir C:\Users\appveyor\AppData\Roaming\Python\Python35\Scripts"

build: off

install:
- "pip install -U --user pip"
- "pip install -U --user tox"
- "pip install -U --user coverage"

test_script:
- "tox -e %TOX_ENV%"
- "coverage report"



