version: 0.1.0.{build}

environment:
  PYTHONUNBUFFERED: 1
  matrix:
    - PYTHON_VERSION: "35"
    - PYTHON_VERSION: "36"
    - PYTHON_VERSION: "37"
      RUN_COVERAGE: "True" # Only run coverage in this version

init:
- "SET PYTHON=Python%PYTHON_VERSION%"
- "SET PATH=C:\\%PYTHON%;C:\\Users\\appveyor\\AppData\\Roaming\\Python\\%PYTHON%\\Scripts;%PATH%"
- "echo %PYTHON%"
- "python -V"

build: off

install:
- "python -m pip install -U --user pip"
- "python -m pip install -U --user tox"
- "python -m pip install -U --user coverage"
- "dir C:\\Users\\appveyor\\AppData\\Roaming\\Python\\%PYTHON%\\Scripts"

test_script:
- "tox -e py%PYTHON_VERSION%"

after_test:
- on:
    RUN_COVERAGE: True
- "coverage run --source=./pycstruct -m unittest discover -s tests/"
- "coverage report"


