# pycstruct appveyor configuration for Linux x64

# Common configuration
image: 
- Ubuntu

platform: x64

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

version: 0.1.0.{build}

install:

build_script:
  - sh: run_tests.sh



